//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resources.rc
//
#define IDS_ERRORLOADINGDOCKLET         1
#define IDS_NOMOREDOCKLETS              2
#define IDS_STYLE0                      3
#define IDS_STYLE1                      4
#define IDS_STYLE2                      5
#define IDS_STYLE3                      6
#define IDS_LABELPOSITION0              7
#define IDS_LABELPOSITION1              8
#define IDS_LABELPOSITION2              9
#define IDS_LABELPOSITION3              10
#define IDS_HALIGN0                     11
#define IDS_HALIGN1                     12
#define IDS_HALIGN2                     13
#define IDS_VALIGN0                     14
#define IDS_VALIGN1                     15
#define IDS_VALIGN2                     16
#define IDS_LABELTYPE0                  17
#define IDS_LABELTYPE1                  18
#define IDS_ERRORSTARTINGAPP            19
#define IDS_LABELTYPE2                  20
#define IDS_QUALITY0                    21
#define IDS_QUALITY1                    22
#define IDS_QUALITY2                    23
#define IDS_QUALITY3                    24
#define IDS_QUALITY4                    25
#define IDS_SINGLECLICK                 26
#define IDS_DOUBLECLICK                 27
#define IDS_TAB0                        28
#define IDS_TAB1                        29
#define IDS_TAB2                        30
#define IDS_CLOSE                       31
#define IDS_ASKDUPLICATE                32
#define IDS_PROPCAPTION                 33
#define IDS_DEFAULTPROPCAPTION          34
#define IDS_NOCONFIGFOREFFECT           35
#define IDS_NOCONFIGFOREFFECTCAPTION    36
#define IDS_PROJNAME                    100
#define IDD_ADDDOCKLET                  101
#define IDS_GLOBALSETTINGSTITLE         101
#define IDR_APPLICATION                 102
#define IDS_MOVINGTABTITLE              102
#define IDS_SELECTINGTABTITLE           103
#define IDR_DESKLETS                    104
#define IDS_CLICKINGTABTITLE            104
#define IDR_DESKLET                     105
#define IDS_TRAYTABTITLE                105
#define IDB_BITMAP1                     106
#define IDS_CURRENTCOLOR                106
#define IDB_BITMAP2                     107
#define IDS_MORECOLORS                  107
#define IDB_BITMAP3                     108
#define IDS_OTHERTABTITLE               108
#define IDB_BITMAP4                     109
#define IDD_ABOUT                       110
#define IDS_EFFECTLET_DESC              110
#define IDD_ACTIVEDOCKLETS              111
#define IDR_MENUACTIVE                  112
#define IDR_IMAGE                       113
#define IDR_IMAGES                      114
#define IDR_DESKLETINFO                 115
#define IDR_DESKLETINFOS                116
#define IDR_OLAYER                      117
#define IDR_OLAYERS                     118
#define IDD_TOOLSCONFIG                 120
#define IDS_SHOWCASE_DESC               121
#define IDR_ShowCase                    122
#define IDD_DOCKLETPROPERTIESTABBED     124
#define IDD_APPEARANCE                  125
#define IDS_SKINENUMERATOR_DESC         126
#define IDD_LABEL                       127
#define IDD_ADVANCED                    128
#define IDD_GLOBALSETTINGS              129
#define IDR_POPUP                       130
#define IDR_SkinEnumerator              131
#define IDS_AVEDESKLETFILE_DESC         132
#define IDR_AveDeskletFile              133
#define IDS_AVETHEMEFILE_DESC           134
#define IDB_BITMAP6                     135
#define IDR_AveThemeFile                136
#define IDS_AVEINSTALLFILE_DESC         137
#define IDR_AveInstallFile              138
#define IDI_ICON1                       139
#define IDS_DESKLETSKIN_DESC            140
#define IDD_LABELCONFIG                 141
#define IDR_DeskletSkin                 142
#define IDS_DESKLETSKINS_DESC           143
#define IDR_DeskletSkins                144
#define IDR_AveDesk                     146
#define IDD_MOVECONFIG                  147
#define IDD_SELECTCONFIG                148
#define IDD_CLICKCONFIG                 149
#define IDD_TRAYCONFIG                  150
#define IDD_OTHERCONFIG                 151
#define IDR_COLORMATRIX                 154
#define IDR_DEBUG                       155
#define IDR_EffectLet                   158
#define IDR_MATRIX                      159
#define IDR_PREFERENCE                  160
#define IDR_PREFERENCES                 161
#define IDR_TIMER                       162
#define IDD_PREFERENCES                 164
#define IDS_TAB5TOOLS                   165
#define IDS_EMPTYTOOL                   166
#define IDS_TOOL                        167
#define IDS_NOSUCHFILE3                 168
#define IDD_SHOWCASECONFIG              168
#define IDS_TOOLNOTFOUND                169
#define IDD_NEWSHADOWPROPERTIES         169
#define IDS_MODULENOCONFIG              170
#define IDD_INSTALLPROGRESS             170
#define IDS_STYLE4                      171
#define IDI_ICON2                       171
#define IDS_MAINLABELSHADOWDLGTITLE     172
#define IDI_ICON3                       172
#define IDS_MAINSUBLABELSHADOWDLGTITLE  173
#define IDI_ICON4                       173
#define IDS_EXPANDED_ENV_STRING         174
#define IDI_ICON5                       174
#define IDS_THEMEDIRCHANGEDQUESTION     175
#define IDD_FILEASSOC_CONFIG            175
#define IDS_INITIALTHEMEDIR             176
#define IDD_MODULES                     176
#define IDS_THEMEDIRBOXCAPTION          177
#define IDD_INSTALLERROR                177
#define IDS_DOWNLOADINGFILE             178
#define IDD_THEMEBROWSER                178
#define IDS_INSTALLINGFILE              179
#define IDD_EFFECTSCONFIG               179
#define IDS_CONNECTING                  180
#define IDS_FILEINSTALLED               181
#define IDS_FILEDOWNLOADED              182
#define IDS_DOWNLOADCANCELED            183
#define IDS_NEWTHEMEFILENAME            184
#define IDS_REMOVEDESKLETQUESTION       185
#define IDS_REMOVEDESKLETCAPTION        186
#define IDS_FILEDOESNOTEXIST            187
#define IDS_DIRECTORYDOESNOTEXIST       188
#define IDS_REQUIREMENTMETERROR         189
#define IDS_AVEDESKVERSIONERROR         190
#define IDS_INSTALLERVERSIONERROR       191
#define IDS_INSTALLERCAPTION            192
#define IDS_PACKAGENOTINSTALLED         193
#define IDS_DESKLETVERSIONERROR         194
#define IDS_THEMESFILTER                195
#define IDS_DESKLETSFILTER              196
#define IDS_NEWTOOLNAME                 197
#define IDS_SELECTSTARTUPFOLDERCAPTION  198
#define IDS_TOOLSARGUMENTSHELPCAPTION   199
#define IDS_TOOLSARGUMENTSHELPTEXT      200
#define IDS_DESKLETCLICKINGDEFAULT      201
#define IDS_DESKLETCLICKINGSINGLE       202
#define IDS_DESKLETCLICKINGDOUBLE       203
#define IDS_DELETETHEME                 204
#define IDS_DELETETHEMECAPTION          205
#define IDS_NOINFO                      206
#define IDS_INFOSTRING                  207
#define IDS_REMOVEDESKLETS              208
#define IDS_REMOVEDESKLETSCAPTION       209
#define IDS_NOINSTALLERFILE             210
#define IDS_INSTALLERFILEINVALID        211
#define IDS_INSTALLERREQUIREMENTSERROR  212
#define IDS_INSTALLERFILENOTCOPIED      213
#define IDS_INSTALLERRIGHTS             214
#define IDC_LIST                        1000
#define IDC_NAME                        1001
#define IDC_AUTHOR                      1002
#define IDC_NOTES                       1003
#define IDADD                           1004
#define IDC_CAPTION                     1005
#define IDC_VERSION                     1005
#define IDC_BUILDDATE                   1006
#define IDC_XPOS                        1007
#define IDC_INSTALLER                   1007
#define IDC_YPOS                        1008
#define IDC_WIDTH                       1009
#define IDC_HEIGHT                      1010
#define IDC_LOCKPOSITION                1011
#define IDC_MARGIN                      1011
#define IDC_ALPHA                       1012
#define IDC_STYLE                       1013
#define IDC_ALPHA2                      1013
#define IDC_IMAGE                       1014
#define IDSETIMAGE                      1015
#define IDDELETEITEM                    1016
#define IDC_ROTATION                    1017
#define IDC_DOWN                        1018
#define IDC_UP                          1019
#define IDC_DOWN2                       1020
#define IDC_UP2                         1021
#define IDSELECTFONT                    1021
#define IDC_RIGHT                       1022
#define IDSELECTCOLOR                   1022
#define IDC_LEFT                        1023
#define IDSELECTFONT2                   1023
#define IDC_RIGHT2                      1024
#define IDC_SHADOW                      1024
#define IDC_LEFT2                       1025
#define IDC_POSITION                    1025
#define IDC_LABELTYPE                   1026
#define IDC_EFFECT                      1026
#define IDC_LABELONLYONMOUSEOVER        1027
#define IDREMOVEIMAGE                   1027
#define IDC_HALIGN2                     1028
#define IDC_VALIGN2                     1029
#define IDSELECTCOLOR2                  1031
#define IDC_LABELBACKGROUND             1032
#define IDC_SHADOW2                     1033
#define IDC_TAB                         1034
#define IDC_QUALITY                     1036
#define IDC_DROPSHADOW                  1037
#define IDC_XOFFSET                     1038
#define IDC_YOFFSET                     1039
#define IDC_GRAY                        1040
#define IDC_IGNORELEFTCLICKS            1041
#define IDC_DRAGDELAY                   1042
#define IDC_COLORIZE                    1042
#define IDC_CLICKINGMODE                1043
#define IDC_IGNORERIGHTCLICKS           1043
#define IDC_GRIDWIDTH                   1044
#define IDC_SNAPTOGRID                  1044
#define IDC_GRIDHEIGHT                  1045
#define IDC_ISCLICKTHRU                 1045
#define IDC_GRIDXMARGIN                 1046
#define IDC_GRIDYMARGIN                 1047
#define IDC_SELECTIONDELAY              1048
#define IDC_SATURATION                  1051
#define IDC_HUE                         1052
#define IDC_RESET                       1053
#define IDC_TOPDOWN                     1054
#define IDCONFIGEFFECT                  1055
#define IDC_HOVERSELECTION              1056
#define IDC_SUBLABEL                    1057
#define IDSETCOLOR                      1060
#define IDCONFIGSUBSHADOW               1063
#define IDCONFIGSHADOW                  1064
#define IDC_STARTUP                     1065
#define IDBROWSEFORICON                 1066
#define IDC_ASK                         1066
#define IDSETDEFAULTICON                1067
#define IDC_AUTOSAVE                    1067
#define IDC_CURICON                     1068
#define IDC_MAKETHUMBNAIL               1068
#define IDC_CURICON2                    1069
#define IDC_ABOUTEFFECTLET              1069
#define IDC_SCROLLBAR                   1070
#define IDC_PREFFRAME                   1071
#define IDC_ROTATIONSPINNER             1073
#define IDC_SHOWTRAY                    1086
#define IDSHADOWCOLOR                   1087
#define IDC_COPYRIGHT                   1088
#define IDC_EDIT_CAPTION                1090
#define IDC_EDIT_COMMAND                1091
#define IDC_EDIT_ARGS                   1092
#define IDC_EDIT_STARTUP_FOLDER         1093
#define IDC_CHECK1                      1094
#define IDC_BUTTON_COMMAND              1095
#define IDC_BUTTON_ARGS                 1096
#define IDC_BUTTON_STARTUP_FOLDER       1097
#define IDC_LISTTOOLS                   1098
#define IDC_HKSHOWCASE                  1099
#define IDC_HKSHOWCASE2                 1100
#define IDC_ALPHALEVEL                  1101
#define IDC_NUMFRAMES                   1102
#define IDBGCOLOR                       1103
#define IDC_DOANIM                      1104
#define IDC_ALPHASPIN                   1108
#define IDC_BLURRATIO                   1109
#define IDC_BLURSPIN                    1110
#define IDC_EDIT1                       1111
#define IDC_XSPIN                       1112
#define IDC_EDIT2                       1113
#define IDC_CAPTIONGROUP                1113
#define IDC_YSPIN                       1114
#define IDC_EDIT3                       1115
#define IDC_SPINX                       1115
#define IDC_WIDTHSPIN                   1116
#define IDC_SPINY                       1116
#define IDC_EDIT4                       1117
#define IDC_SPINWIDTH                   1117
#define IDC_HEIGHTSPIN                  1118
#define IDC_SPINHEIGHT                  1118
#define IDC_SLIDERALPHA                 1119
#define IDC_SPINALPHA                   1120
#define IDC_SLIDERROTATION              1121
#define IDC_SPINROTATION                1122
#define IDC_TREE                        1123
#define IDC_INTENSITY                   1124
#define IDC_SPININTENSITY               1125
#define IDC_ISENABLED                   1126
#define IDC_MESSAGE                     1131
#define IDC_PROGRESSBAR                 1132
#define IDC_LINK                        1134
#define IDC_AVE                         1135
#define IDC_HERD                        1136
#define IDC_MIKEGRAPHIK                 1137
#define IDC_KOL                         1137
#define IDC_ABOUTICON                   1138
#define IDC_ASSOCDESKLET                1139
#define IDCHANGEICONDESKLET             1140
#define IDRESETICONDESKLET              1141
#define IDC_MODULESLIST                 1141
#define IDC_UNINSTALL                   1143
#define IDC_INSTALL                     1144
#define IDC_ERRORTEXT                   1144
#define IDC_CLOSE                       1145
#define IDC_ERRORLINK                   1145
#define IDC_ERRORICON                   1146
#define IDC_ERRORLINKTEXT               1147
#define IDC_STATIC_MENU_CAPTION         1148
#define IDC_STATIC_COMMAND              1149
#define IDC_STATIC_ARGS                 1150
#define IDC_STATIC_STARTUP_FOLDER       1151
#define IDC_DOTRAYANIMATION             1152
#define IDC_ANIMATIONS                  1153
#define IDC_CLICKING                    1154
#define IDC_THEMES                      1155
#define IDC_ENABLEFLIP                  1156
#define IDC_FLIPSPEED                   1157
#define IDC_STATIC_FLIP_SPEED           1158
#define IDC_STATIC_FLIP_SLOW            1159
#define IDC_STATIC_FLIP_FAST            1160
#define IDBUTRESETFLIP                  1161
#define IDC_CLOSESPEED                  1162
#define IDC_STATIC_CLOSE_SPEED          1163
#define IDC_STATIC_CLOSE_SLOW           1164
#define IDC_STATIC_CLOSE_FAST           1165
#define IDBUTRESETCLOSE                 1166
#define IDC_CLOSEFADEOUT                1169
#define IDC_ENABLECLOSE                 1170
#define IDC_LOADTHEME                   1171
#define IDC_DELETETHEME                 1172
#define IDC_CLOSEWINDOW                 1173
#define IDC_SHOWCASEISCLICKTHRU         1173
#define IDM_APPLICATION_EXIT            40001
#define IDM_DESKLETS_ADD                40002
#define IDM_DESKLETS_REMOVE             40003
#define IDM_DESKLETS_PROPERTIES         40004
#define IDM_HELP_INDEX                  40005
#define IDM_HELP_ABOUT                  40006
#define IDM_SETTINGS_DEFAULTDESKLETPROPERTIES 40008
#define IDM_DESKLETS_AUTOALIGN          40009
#define IDM_DESKLETS_MINIMAL_PROPERTIES 40011
#define ID_SETTINGS_GLOBALSETTINGS      40012
#define ID_CLOSE                        40014
#define ID_ABOUT                        40016
#define IDM_APPLICATION_SAVECONFIGURATION 40018
#define ID_DESKLETSCONTROLPANEL         40019
#define ID_DESKLETPOPUPMENU_DESKLETPROPERTIES 40020
#define ID_DESKLETPOPUPMENU_REMOVEDESKLET 40021
#define ID_DESKLETPOPUPMENU_LOCKPOSITION 40022
#define ID_DESKLETPOPUPMENU_CONTROLPANEL 40024
#define ID_DESKLETPOPUPMENU_DUPLICATETHISDESKLET 40025
#define ID_DESKLETS_DUPLICATE           40026
#define ID_DESKLETPOPUPMENU_SHOWSUBLABEL 40027
#define ID_EXTRAS_TOOL0                 40029
#define ID_EXTRAS_TOOL1                 40030
#define ID_EXTRAS_TOOL2                 40031
#define ID_EXTRAS_TOOL3                 40032
#define ID_EXTRAS_TOOL4                 40033
#define ID_EXTRAS_TOOL5                 40034
#define ID_EXTRAS_TOOL6                 40035
#define ID_EXTRAS_TOOL7                 40036
#define ID_EXTRAS_TOOL8                 40037
#define ID_EXTRAS_TOOL9                 40038
#define ID_EXTRAS_MODIFYTOOLS           40040
#define ID_EXTRAS_MODULES_MODULE0       40041
#define ID_EXTRAS_MANAGETOOLS           40042
#define ID_TOOLSPOPUPMENU_RENAME        40043
#define ID_TOOLSPOPUPMENU_REMOVE        40044
#define ID_TOOLSPOPUPMENU_ADDNEW        40045
#define ID_TOOLSPOPUPMENU_MOVEUP        40046
#define ID_TOOLSPOPUPMENU_MOVEDOWN      40047
#define IDM_SAVECONFIGAS                40048
#define IDM_LOADCONFIG                  40049
#define ID_LOADTHEME                    40052
#define IDM_CREATEEMPTYTHEME            40055
#define IDM_EXPORTDESKLET               40056
#define IDM_IMPORTDESKLET               40057
#define ID_OPENBROWSER                  40058
#define ID_OPENSHOWCASE                 40059
#define ID_CLOSESHOWCASE                40060
#define ID_EXTRAS_MODULES_MODULE        50000
#define ID_EXTRAS_MODULES_MODULE_MAX    50255

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         40062
#define _APS_NEXT_CONTROL_VALUE         1174
#define _APS_NEXT_SYMED_VALUE           145
#endif
#endif
